AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.2
  TargetRailsVersion: 4.2
  Exclude:
    - 'bin/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/*.rake'

Metrics/LineLength:
  Max: 100

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false
