inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.2
  Exclude:
    - 'bin/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Layout/TrailingBlankLines:
  Exclude:
    - 'Gemfile'

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'app/admin/**/*'
    - 'lib/tasks/*.rake'
    - 'spec/**/*'

Metrics/LineLength:
  Max: 100

Naming/FileName:
  Exclude:
    - 'app/views/**/*'

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false
