default: &default
  omniauth_provider_key: <%= ENV.fetch("OMNIAUTH_PROVIDER_KEY") %>
  omniauth_provider_secret: <%= ENV.fetch("OMNIAUTH_PROVIDER_SECRET") %>
  secret_key_base: <%= ENV.fetch("SECRET_KEY_BASE") %>

development:
  <<: *default
  secret_key_base: 7a64cdc5282420a9605196fc96eb474e2e2d0dece2bb0363473dac4d877150a648488ccef89dacaabed61e645ec0098aa642c8d17951ecd03776dd405fec72ee

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
