default: &default
  omniauth_provider_key: <%= ENV["OMNIAUTH_PROVIDER_KEY"] %>
  omniauth_provider_secret: <%= ENV["OMNIAUTH_PROVIDER_SECRET"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

development:
  <<: *default
  secret_key_base: 7a64cdc5282420a9605196fc96eb474e2e2d0dece2bb0363473dac4d877150a648488ccef89dacaabed61e645ec0098aa642c8d17951ecd03776dd405fec72ee
  omniauth_provider_key: e583d874a5046a0cf1ff
  omniauth_provider_secret: 71b53394a0414166eeca8cdb29270abb2940cf6a

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
